"""empty message

Revision ID: 1f7fb26f275f
Revises: 2e4abe3cc748
Create Date: 2021-07-02 09:32:33.654248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7fb26f275f'
down_revision = '2e4abe3cc748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hunt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=True),
    sa.Column('ans', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'user', ['password'])
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_table('hunt')
    # ### end Alembic commands ###
