"""empty message

Revision ID: 2e4abe3cc748
Revises: 5de2a3c1ec18
Create Date: 2021-07-01 11:45:36.332648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4abe3cc748'
down_revision = '5de2a3c1ec18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'user', ['password'])
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
